window.SENTENCES_AUDIO_MAP = {
  "Collect all carrots starting with Ff": "assets/audios/sentences/bunny_collect_ff.mp3",
  "Find words starting with Ff": "assets/audios/sentences/bunny_find_ff.mp3",
  "Find words starting with letter Ff": "assets/audios/sentences/bunny_find_let_ff.mp3",
  "Collect all carrots starting with Dd": "assets/audios/sentences/bunny_collect_dd.mp3",
  "Find words starting with Dd": "assets/audios/sentences/bunny_find_dd.mp3",
  "Find words starting with letter Dd": "assets/audios/sentences/bunny_find_let_dd.mp3",
  "Collect all carrots starting with Hh": "assets/audios/sentences/bunny_collect_hh.mp3",
  "Find words starting with Hh": "assets/audios/sentences/bunny_find_hh.mp3",
  "Find words starting with letter Hh": "assets/audios/sentences/bunny_find_let_hh.mp3",
  "Collect all carrots starting with Rr": "assets/audios/sentences/bunny_collect_rr.mp3",
  "Find words starting with Rr": "assets/audios/sentences/bunny_find_rr.mp3",
  "Find words starting with letter Rr": "assets/audios/sentences/bunny_find_let_rr.mp3",
  "Collect all carrots starting with Ss": "assets/audios/sentences/bunny_collect_ss.mp3",
  "Find words starting with Ss": "assets/audios/sentences/bunny_find_ss.mp3",
  "Find words starting with letter Ss": "assets/audios/sentences/bunny_find_let_ss.mp3",
  "Collect all carrots starting with Jj": "assets/audios/sentences/bunny_collect_jj.mp3",
  "Find words starting with Jj": "assets/audios/sentences/bunny_find_jj.mp3",
  "Find words starting with letter Jj": "assets/audios/sentences/bunny_find_let_jj.mp3",
  "Collect all carrots starting with Kk": "assets/audios/sentences/bunny_collect_kk.mp3",
  "Find words starting with Kk": "assets/audios/sentences/bunny_find_kk.mp3",
  "Find words starting with letter Kk": "assets/audios/sentences/bunny_find_let_kk.mp3",
  "Kim has a fish. The fish can swim. ... What can the fish do?": "assets/audios/sentences/bunny_act_1ad7d915.mp3",
  "Ted has a rabbit. The rabbit can hop. ... What can the rabbit do?": "assets/audios/sentences/bunny_act_6f92ee50.mp3",
  "Diego has a dog. The dog can run. ... What can the dog do?": "assets/audios/sentences/bunny_act_783a2af3.mp3",
  "Paul has an owl. The owl can fly. ... What can the owl do?": "assets/audios/sentences/bunny_act_d86ba39e.mp3",
  "Zac has a duck. The duck can walk. ... What can the duck do?": "assets/audios/sentences/bunny_act_f98776d4.mp3"
};
